### ISSUE TITLE
Draft_RIKEN_IMS.ttlへのコメント

### ISSUE THREAD

**Issue by okbp** [systemsomicslab/MassBank-RDF#1]
20240703版でざっと気になった所をリストアップします。
https://github.com/systemsomicslab/MassBank-RDF/blob/3368d51773ca456d2fcac678a1de1ef9b1913472/draft_ttl/Draft_RIKEN_IMS.ttl

* prefixの定義が足りていない
http://ttl.summerofcode.be/ で簡易チェックが可能
  * @prefix classyfire:
  * @prefix pk:
  * @prefix pkano:

* 主語になっているものには rdf:type があった方がいい。"このURIの実体はなんであるか"を検討して、適切なクラスを選択する。適切なクラスがなければ、独自にOntologyを定義する必要がある。
```
mb:MSBNK-RIKEN_IMS-LQA00001_DE
    # こういうところにrdf:typeがあった方がいい(全体的に)
    mbo:has_descripter [
```
* URIがテキストになっている(ダブルクォーテーションで囲まれている)箇所ある。これはSPARQLで繋がらないので、修正する
```
mbo:has_classyfire_taxon [
    rdf:type classyfire:kingdom;
    sio:SIO_000300 "co:CHEMONTID:0000000" #ここは テキストだと繋がらない
(略)
    rdf:type sio:SIO_000811;
    sio:SIO_000300 "http://classyfire.wishartlab.com/tax_nodes/C0000000" #ここは テキストだと繋がらない
 
```
* 数値データであるなら文字列にしない
```
 rdf:type sio:CHEMINF_000217;
    sio:SIO_000300 "793.525767"; # 確実に数値データなら、数値型にする(ダブルクォーテーションで囲まない)
    sio:SIO_000221 obo:UO_0000055
```
* このprefixはsioではないのでは？
```
    mbo:has_descripter [
    rdf:type sio:CHEMINF_000043; # prefixはsioではないのでは？
    sio:SIO_000300 "PC(14:0/10-HDoHE)"
```
SIOのOWL: https://raw.githubusercontent.com/micheldumontier/semanticscience/master/ontology/sio/release/sio-release.owl

**Comment by kozo2** [comment]
@okbp 
> prefixの定義が足りていない

すみません、スキーマを大幅に変えることにしたのでこのご助言についてはスキップすることをお許しください。

> 主語になっているものには rdf:type があった方がいい。

https://github.com/systemsomicslab/MassBank-RDF/blob/main/draft_ttl/nishida/MSBNK-CASMI_2016-SM828451.ttl
では 主語に必ず rdf:type をつけるようにしました。

**Comment by kozo2** [comment]
@okbp 
> URIがテキストになっている(ダブルクォーテーションで囲まれている)箇所ある。これはSPARQLで繋がらないので、修正する

https://github.com/systemsomicslab/MassBank-RDF/blob/main/draft_ttl/nishida/MSBNK-CASMI_2016-SM828451.ttl ではそのURIテキスト問題を修正しました。

**Comment by kozo2** [comment]
@okbp 
> 数値データであるなら文字列にしない

```
massbank:MSBNK-CASMI_2016-SM828451\#ChemicalSubstance schema:monoisotopicMolecularWeight "224.04734"^^xsd:double .
```

でも文字列のままなのですが、`^^xsd:double` 等をつけるようにしました。

**Comment by kozo2** [comment]
@okbp 
> このprefixはsioではないのでは？

その問題を含むコードを https://github.com/systemsomicslab/MassBank-RDF/blob/main/draft_ttl/nishida/MSBNK-CASMI_2016-SM828451.ttl では取り除きました。
